#!/bin/bash
UUID=$(/usr/bin/facter sp_platform_uuid)
/bin/cp /private/tmp/puppetcerts/ca.pem /etc/puppet/ssl/certs/ca.pem
/bin/cp /private/tmp/puppetcerts/puppetcert.pem /etc/puppet/ssl/certs/${UUID}.pem
/bin/cp /private/tmp/puppetcerts/private_key.pem /etc/puppet/ssl/private_keys/${UUID}.pem

/usr/bin/srm -rf /private/tmp/puppetcerts
/usr/sbin/chown puppetdb:puppetdb /etc/puppetdb/ssl/*.pem
/bin/chmod 0600 /etc/puppetdb/ssl/*.pem

