PKGVERSION=1.0.0
PKGNAME="java_se_fix"
PKGID=edu.whitby.java_se_fix

build: 
	mkdir -p out
	pkgbuild --root pkgroot --identifier ${PKGID} --version ${PKGVERSION} --scripts scripts out/${PKGNAME}-${PKGVERSION}.pkg
	
