#!/bin/bash

PKG_VERSION=1.5.25.gcbb1ac6
DNSUPDATER='/Library/Application Support/OpenDNS Roaming Client/dns-updater'
if [ ! -e "$DNSUPDATER" ]; then
  #if file doesn't exist, exit. Munki will install OpenDNS
  exit 0
else
  version=`"$DNSUPDATER" --version`
  if [ ${version:-0} \< $PKG_VERSION ]; then
    #version is less than the package version. Munki will install OpenDNS
    exit 0
  else
    # The latest version is already installed. skip
    exit 1
  fi
fi



