USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=logstash-forwarder
PACKAGE_NAME=${TITLE}
REVERSE_DOMAIN=com.elasticsearch
PACKAGE_VERSION=0.3.1
PAYLOAD=\
	pack-usr-local-bin-logstash-forwarder
