PKGVERSION=1.0.3
PKGNAME="yo_trigger"
PKGID=com.github.groob.yo_trigger

build: 
	mkdir -p out
	pkgbuild --root pkgroot --identifier ${PKGID} --version ${PKGVERSION} --scripts scripts out/${PKGNAME}-${PKGVERSION}.pkg
	
