PKGVERSION=1.0.0
PKGNAME="yo_office2016"
PKGID=edu.whitby.yo.office2016

build: 
	mkdir -p out
	pkgbuild --root pkgroot --identifier ${PKGID} --version ${PKGVERSION} --scripts scripts out/${PKGNAME}-${PKGVERSION}.pkg
	
